/*
  © 2026 Wayne Cavanagh / Flaux. All rights reserved.
  3D movement data, pulling, arms and carries: see js/moves/README.md.
*/
const FEET = { L: { foot: [0.12, 0.07, 0], toeOut: 8 }, R: 'mirror' };
const DB2 = [{ type: 'dumbbell', hand: 'L' }, { type: 'dumbbell', hand: 'R' }];

// Walking on the spot for the carries: each foot lifts and sets down on its
// own mark (so nothing slides), the pelvis shifts a little over the standing
// leg, and any free arm swings against the opposite leg. `arms(phase)` gives
// the arms for 'L' (left foot up), 'R' (right foot up) and 'both'.
function walk(arms, extra = {}) {
  const foot = (x) => ({ foot: [x, 0.07, 0], toeOut: 6 });
  const lift = (x) => ({ foot: [x, 0.19, -0.04], knee: 'fwd', toeOut: 6, ankle: -8 });
  return {
    both: { label: 'Walk tall', ...extra, pelvis: { pos: [0, 0.925, 0] },
      legs: { L: foot(0.11), R: foot(-0.11) }, arms: arms('both') },
    liftL: { label: 'Left step', ...extra, pelvis: { pos: [-0.025, 0.93, 0.005] },
      legs: { L: lift(0.11), R: foot(-0.11) }, arms: arms('L') },
    liftR: { label: 'Right step', ...extra, pelvis: { pos: [0.025, 0.93, 0.005] },
      legs: { L: foot(0.11), R: lift(-0.11) }, arms: arms('R') },
  };
}
const WALK_SEQ = ['both', 'liftL', 'both', 'liftR'];
const WALK_TEMPO = 0.3;
const WALK_HOLDS = { both: 0, liftL: 0.02, liftR: 0.02 };
// a free arm swinging against the legs: forward when the other foot is up
const swing = (side, phase) => {
  if (phase === 'both') return { shoulder: { elev: 6, plane: 90 }, elbow: 12 };
  const fwd = (side === 'L') === (phase === 'R');
  return fwd ? { shoulder: { elev: 22, plane: 8 }, elbow: 22 } : { shoulder: { elev: 16, plane: 172 }, elbow: 8 };
};

// dumbbell curls: upper arms still, the forearms swing up in an arc.
// turn sets the grip: 90 palms up (a curl), 0 palms in (a hammer curl)
const curlKeys = (turn) => ({
  down: { label: 'Arms long', legs: FEET,
    arms: { L: { shoulder: { elev: 4, plane: 0 }, elbow: 8, turn }, R: 'mirror' } },
  up: { label: 'Squeeze', legs: FEET,
    arms: { L: { shoulder: { elev: 10, plane: 0 }, elbow: 138, turn }, R: 'mirror' } },
});

export default {
  dbCurl: {
    camera: { yaw: 40 },
    props: DB2,
    muscles: { primary: ['biceps'], secondary: ['forearms'] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart and a dumbbell in each hand.',
        'Arms long by your sides, palms turned to face forward.',
        'Upper arms close to the ribs, shoulders relaxed down.',
      ],
      steps: [
        'Keep the elbows still and bend them to bring the dumbbells up in an arc.',
        'Curl until the forearms are close to the upper arms and the dumbbells are near the shoulders.',
        'Squeeze the biceps for a moment at the top.',
        'Lower slowly all the way back to straight arms.',
      ],
      cues: ['Elbows pinned to the ribs', 'Slow on the way down', 'Stand still, no swinging'],
      mistakes: [
        'Swinging the body to throw the weight up, which takes the work off the biceps.',
        'Elbows drifting forward so the shoulders do the lifting.',
        'Stopping short of straight arms at the bottom and missing half the range.',
        'Bending the wrists back as you curl.',
      ],
      breathing: 'Breathe out as you curl up, breathe in as you lower.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: curlKeys(90),
    seq: ['down', 'up'], tempo: [1.0, 2.0], holds: { up: 0.35, down: 0.3 },
  },
  dbHammerCurl: {
    camera: { yaw: 40 },
    props: DB2,
    muscles: { primary: ['biceps', 'forearms'], secondary: [] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart and a dumbbell in each hand.',
        'Arms long by your sides with the palms facing your thighs, like holding two hammers.',
        'Upper arms close to the ribs, shoulders relaxed down.',
      ],
      steps: [
        'Keep the palms facing in and bend the elbows to curl the dumbbells up.',
        'Keep the elbows still at your sides as the forearms rise.',
        'Stop when the dumbbells are near the front of the shoulders and squeeze.',
        'Lower slowly back to straight arms without letting the palms turn.',
      ],
      cues: ['Palms facing in the whole way', 'Elbows stay by your sides', 'Control the lowering'],
      mistakes: [
        'Letting the wrists rotate so it turns into a normal curl.',
        'Swinging the hips or leaning back to get the weight moving.',
        'Elbows drifting forward and up at the top.',
        'Dropping the dumbbells quickly instead of lowering them.',
      ],
      breathing: 'Breathe out as you curl up, breathe in as you lower.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: curlKeys(0),
    seq: ['down', 'up'], tempo: [1.0, 2.0], holds: { up: 0.35, down: 0.3 },
  },
  barbellCurl: {
    camera: { yaw: 40 },
    props: [{ type: 'barbell', length: 1.5, plate: 0.13 }],
    muscles: { primary: ['biceps'], secondary: ['forearms'] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart, bar resting against the front of the thighs.',
        'Hands about shoulder-width apart, palms facing forward.',
        'Upper arms by the ribs, shoulders down and back, glutes lightly switched on.',
      ],
      steps: [
        'Keep the elbows fixed at your sides and curl the bar up in an arc.',
        'Bring the bar to just below the collarbones without letting the elbows travel forward.',
        'Squeeze the biceps for a moment at the top.',
        'Lower slowly until the arms are straight and the bar is back at the thighs.',
      ],
      cues: ['Elbows pinned', 'No hip swing', 'All the way down'],
      mistakes: [
        'Leaning back and using the hips to heave the bar up.',
        'Elbows sliding forward so the front of the shoulders takes over.',
        'Cutting the bottom of the rep short.',
        'Letting the wrists curl back under the weight of the bar.',
      ],
      breathing: 'Breathe out as you curl up, breathe in as you lower.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: {
      down: { label: 'Arms long', legs: FEET,
        arms: { L: { shoulder: { elev: 12, plane: 20 }, elbow: 8 }, R: 'mirror' } },
      up: { label: 'Squeeze', legs: FEET,
        arms: { L: { shoulder: { elev: 12, plane: 12 }, elbow: 138 }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [1.0, 2.0], holds: { up: 0.35, down: 0.3 },
  },
  dbShrug: {
    camera: { yaw: 20 },
    props: DB2,
    muscles: { primary: ['traps'], secondary: ['forearms', 'upperBack'] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart, a dumbbell in each hand at your sides.',
        'Palms facing your thighs, arms long and relaxed.',
        'Chin tucked slightly so the neck stays long.',
      ],
      steps: [
        'Lift the shoulders straight up towards the ears.',
        'Hold the top for a beat and squeeze the upper traps.',
        'Lower the shoulders slowly all the way down to a full stretch.',
        'Keep the arms straight the whole time: they just hang and carry the weight.',
      ],
      cues: ['Straight up, straight down', 'Hold a beat at the top', 'Arms stay long'],
      mistakes: [
        'Rolling the shoulders in circles, which adds nothing and strains the joint.',
        'Bending the elbows to pull the weight up.',
        'Poking the chin forward as the shoulders rise.',
        'Bouncing through fast reps with no pause at the top.',
      ],
      breathing: 'Breathe out as you shrug up, breathe in as you lower.',
      tempo: 'About 1 second up, hold 1 second, 2 seconds down.',
    },
    keys: {
      down: { label: 'Arms long', legs: FEET,
        arms: { L: { shoulder: { elev: 7, plane: 90 }, elbow: 4, turn: 90 }, R: 'mirror' } },
      up: { label: 'Shoulders up', legs: FEET, neck: { flex: 8 },
        arms: { L: { shoulder: { elev: 7, plane: 90 }, elbow: 2, turn: 90, shrug: 0.045 }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [0.8, 1.4], holds: { up: 0.8, down: 0.3 },
  },
  dbUprightRow: {
    camera: { yaw: 30 },
    props: DB2,
    muscles: { primary: ['shoulders', 'traps'], secondary: ['biceps', 'upperBack'] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart, dumbbells in front of the thighs.',
        'Palms facing your legs, hands about shoulder-width apart.',
        'Brace the trunk and keep the shoulders down away from the ears.',
      ],
      steps: [
        'Lead with the elbows and lift them up and out to the sides.',
        'Keep the dumbbells close to the body as they rise.',
        'Stop when the elbows reach shoulder height, with the elbows above the hands.',
        'Lower slowly back to the thighs.',
      ],
      cues: ['Elbows lead', 'Stop at shoulder height', 'Dumbbells close to the body'],
      mistakes: [
        'Pulling the elbows higher than the shoulders, which can pinch the front of the shoulder.',
        'Letting the hands get higher than the elbows.',
        'Leaning back or using the legs to swing the weight up.',
        'Shrugging the shoulders up to the ears.',
      ],
      breathing: 'Breathe out as you lift, breathe in as you lower.',
      tempo: 'About 1 second up, a short pause, 2 seconds down.',
    },
    keys: {
      down: { label: 'Arms long', legs: FEET, arms: { L: { hand: [0.12, 0.84, 0.09], elbow: [1, 0, 0] }, R: 'mirror' } },
      up: { label: 'Elbows high', legs: FEET, arms: { L: { hand: [0.12, 1.22, 0.1], elbow: [1, 0.5, 0] }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [1.0, 1.8], holds: { up: 0.3, down: 0.3 },
  },
  kbRackHold: {
    camera: { yaw: 30 },
    props: [{ type: 'kettlebell', hand: 'R', grip: 'auto' }],
    muscles: { primary: ['core'], secondary: ['shoulders', 'upperBack', 'forearms'] },
    coaching: {
      setup: [
        'Clean or lift the kettlebell into the front rack: handle in the palm, bell resting on the outside of the forearm and against the chest.',
        'Elbow tucked down in front of the ribs, wrist straight.',
        'Stand tall with feet hip-width apart and the free arm relaxed by your side.',
      ],
      steps: [
        'Stack the ribs over the pelvis and squeeze the glutes lightly.',
        'Keep the shoulders level: do not lean away from the bell.',
        'Breathe slowly into the belly while the trunk stays braced.',
        'Hold for the set time, then swap sides for the same time.',
      ],
      cues: ['Stand tall', 'Elbow tucked, wrist straight', 'Slow breaths behind a braced trunk'],
      mistakes: [
        'Leaning back or to the side to balance the bell.',
        'Letting the wrist bend back so the bell hangs off the hand.',
        'Elbow flaring out to the side, which drops the bell off the chest.',
        'Holding the breath for the whole set.',
      ],
      breathing: 'Short, steady breaths in through the nose and out through the mouth, keeping the brace.',
      tempo: 'Hold for the set time, around 20 to 40 seconds a side.',
    },
    keys: {
      a: { label: 'Breathe in', legs: FEET, spine: { flex: -1.5 },
        arms: { L: { shoulder: { elev: 6, plane: 90 }, elbow: 10 }, R: { hand: [-0.1, 1.18, 0.15], elbow: [-0.05, -1, 0.35] } } },
      b: { label: 'Breathe out', legs: FEET, spine: { flex: 0.5 },
        arms: { L: { shoulder: { elev: 5, plane: 90 }, elbow: 10 }, R: { hand: [-0.1, 1.175, 0.15], elbow: [-0.05, -1, 0.35] } } },
    },
    seq: ['a', 'b'], tempo: [1.8, 2.2], holds: { a: 0.3, b: 0.4 },
  },
  kbSuitcaseHold: {
    camera: { yaw: 20 },
    props: [{ type: 'kettlebell', hand: 'R', grip: 'hang' }],
    muscles: { primary: ['core', 'obliques'], secondary: ['forearms', 'traps'] },
    coaching: {
      setup: [
        'Stand tall with feet hip-width apart and the kettlebell in one hand at your side.',
        'Arm long, handle gripped firmly, bell just clear of the thigh.',
        'Free arm relaxed by your side.',
      ],
      steps: [
        'Stand as tall as you can with the shoulders level.',
        'Brace the trunk so you do not tip towards the bell.',
        'Keep the loaded shoulder down and away from the ear.',
        'Hold for the set time, then swap hands and repeat.',
      ],
      cues: ['Shoulders level', 'Do not lean', 'Grip hard'],
      mistakes: [
        'Leaning towards the bell, which lets the trunk off the hook.',
        'Leaning away from the bell to over-correct.',
        'Shrugging the loaded shoulder up.',
        'Letting the hips shift out to the side.',
      ],
      breathing: 'Steady breaths behind a braced trunk, no breath holding.',
      tempo: 'Hold for the set time, around 20 to 40 seconds a side.',
    },
    keys: {
      a: { label: 'Breathe in', legs: FEET, spine: { flex: -1.5 },
        arms: { L: { shoulder: { elev: 6, plane: 90 }, elbow: 10 }, R: { shoulder: { elev: 11, plane: 90 }, elbow: 2 } } },
      b: { label: 'Breathe out', legs: FEET, spine: { flex: 0.5 },
        arms: { L: { shoulder: { elev: 5, plane: 90 }, elbow: 10 }, R: { shoulder: { elev: 11, plane: 90 }, elbow: 2 } } },
    },
    seq: ['a', 'b'], tempo: [1.8, 2.2], holds: { a: 0.3, b: 0.4 },
  },
  barbellRow: {
    camera: { yaw: 60 },
    props: [{ type: 'barbell', length: 1.5, plate: 0.13 }],
    muscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'lowerBack', 'hamstrings', 'forearms'] },
    coaching: {
      setup: [
        'Feet hip-width apart, bar over the middle of the feet.',
        'Hands just outside the knees, palms facing back.',
        'Soften the knees and push the hips back until the chest is leaning forward about 45 degrees, back flat.',
        'Let the bar hang at arm\'s length below the shoulders.',
      ],
      steps: [
        'Brace the trunk so the back stays flat and the hips stay put.',
        'Drive the elbows back and up past the ribs.',
        'Pull the bar to the belly button and squeeze the shoulder blades together.',
        'Lower under control to straight arms without letting the chest drop.',
      ],
      cues: ['Flat back, hips back', 'Pull to the belly button', 'Elbows back, not out'],
      mistakes: [
        'Rounding the lower back as the bar comes down.',
        'Standing up more each rep so it turns into a shrug.',
        'Jerking the bar up with the hips instead of pulling with the back.',
        'Flaring the elbows straight out to the sides.',
      ],
      breathing: 'Breathe in and brace before the pull, breathe out as the bar reaches the belly.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Arms long', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.23, 0.63, 0.12], elbow: 'back' }, R: 'mirror' } },
      top: { label: 'Bar to belly', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.23, 0.95, 0.06], elbow: [0.25, 0.6, -1] }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  dbRow: {
    camera: { yaw: 60 },
    props: DB2,
    muscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'lowerBack', 'hamstrings', 'forearms'] },
    coaching: {
      setup: [
        'Feet hip-width apart, a dumbbell in each hand.',
        'Soften the knees and push the hips back until the chest leans forward about 45 degrees, back flat.',
        'Let the dumbbells hang below the shoulders, palms facing back or facing in.',
      ],
      steps: [
        'Brace the trunk and keep the neck in line with the back.',
        'Drive both elbows back towards the hips.',
        'Squeeze the shoulder blades together at the top.',
        'Lower under control to straight arms.',
      ],
      cues: ['Squeeze the blades', 'Elbows to the hips', 'Chest stays still'],
      mistakes: [
        'Rounding the back or letting the chest rise with each rep.',
        'Pulling with the hands and wrists instead of the elbows.',
        'Shrugging the shoulders up towards the ears.',
        'Cutting the lowering short.',
      ],
      breathing: 'Breathe out as you pull, breathe in as you lower.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Arms long', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.22, 0.63, 0.12], elbow: 'back' }, R: 'mirror' } },
      top: { label: 'Squeeze', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.23, 0.95, 0.01], elbow: [0.2, 0.6, -1] }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  kbRow: {
    camera: { yaw: 60 },
    props: [{ type: 'kettlebell', hand: 'R' }],
    muscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'core', 'forearms'] },
    coaching: {
      setup: [
        'Stagger the feet with the non-working foot forward.',
        'Hinge at the hips with a flat back and rest the free hand on the front thigh.',
        'Kettlebell in the working hand, hanging below the shoulder.',
      ],
      steps: [
        'Brace the trunk and keep the hips and shoulders square to the floor.',
        'Drive the elbow back towards the hip, keeping it close to the body.',
        'Pause with the bell beside the ribs and squeeze the shoulder blade back.',
        'Lower slowly to a long arm, then repeat and swap sides.',
      ],
      cues: ['Elbow to the hip', 'Hips and shoulders square', 'Long arm at the bottom'],
      mistakes: [
        'Twisting the chest open to swing the bell up.',
        'Pulling the elbow out wide instead of back to the hip.',
        'Rounding the back as the bell lowers.',
        'Shrugging the shoulder towards the ear.',
      ],
      breathing: 'Breathe out as you row, breathe in as you lower.',
      tempo: 'About 1 second up, a short pause, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Arm long', pelvis: { pos: [0, 0.84, -0.2], pitch: 55 }, neck: { flex: -16 },
        legs: { L: { foot: [0.14, 0.07, 0.14], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.14, 0.07, -0.34], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.14, 0.62, 0.12], elbow: [1, 0, -0.3] }, R: { hand: [-0.2, 0.62, 0.14], elbow: 'back' } } },
      top: { label: 'Elbow to hip', pelvis: { pos: [0, 0.84, -0.2], pitch: 55 }, neck: { flex: -16 },
        legs: { L: { foot: [0.14, 0.07, 0.14], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.14, 0.07, -0.34], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.14, 0.62, 0.12], elbow: [1, 0, -0.3] }, R: { hand: [-0.21, 0.9, -0.04], elbow: [-0.1, 0.5, -1] } } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  dbRowSingle: {
    camera: { yaw: -50, pitch: 10 },
    props: [{ type: 'dumbbell', hand: 'R' }, { type: 'bench', pos: [0.28, 0, 0.8], size: [0.35, 0.45, 1.2] }],
    muscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'core', 'forearms'] },
    coaching: {
      setup: [
        'Stand beside the end of a bench, one hand flat on it and the same-side foot forward.',
        'Other foot back, knees soft, back flat and close to parallel with the floor.',
        'Dumbbell in the working hand, hanging straight below the shoulder.',
      ],
      steps: [
        'Brace the trunk and keep the shoulders square to the floor.',
        'Let the arm reach long at the bottom for a full stretch.',
        'Drive the elbow back towards the hip, dumbbell close to the body.',
        'Pause at the top, then lower slowly to a long arm. Swap sides after the set.',
      ],
      cues: ['Hand on the bench, long pull', 'Elbow to the hip', 'Shoulders square'],
      mistakes: [
        'Twisting the chest up to heave the weight.',
        'Leaning weight onto the bench arm so the back rounds.',
        'Short, jerky pulls that skip the stretch at the bottom.',
        'Pulling the elbow out wide.',
      ],
      breathing: 'Breathe out as you row, breathe in as you lower.',
      tempo: 'About 1 second up, a short pause, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Long arm', pelvis: { pos: [0, 0.82, -0.2], pitch: 72 }, neck: { flex: -10 },
        legs: { L: { foot: [0.15, 0.07, 0.05], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.15, 0.07, -0.4], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.24, 0.48, 0.3], elbow: 'back', palm: 'floor' }, R: { hand: [-0.2, 0.46, 0.25], elbow: 'back' } } },
      top: { label: 'Elbow to hip', pelvis: { pos: [0, 0.82, -0.2], pitch: 72 }, neck: { flex: -10 },
        legs: { L: { foot: [0.15, 0.07, 0.05], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.15, 0.07, -0.4], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.24, 0.48, 0.3], elbow: 'back', palm: 'floor' }, R: { hand: [-0.21, 0.8, -0.05], elbow: [-0.1, 0.6, -1] } } },
    },
    seq: ['hang', 'top'], tempo: [1.1, 1.8], holds: { top: 0.4, hang: 0.3 },
  },
  dbRearDeltFly: {
    camera: { yaw: 30, pitch: 14 },
    props: DB2,
    muscles: { primary: ['shoulders', 'upperBack'], secondary: ['traps'] },
    coaching: {
      setup: [
        'Hold light dumbbells, feet hip-width apart.',
        'Hinge at the hips until the chest is close to parallel with the floor, back flat, knees soft.',
        'Let the dumbbells hang below the chest, palms facing each other, elbows slightly bent.',
      ],
      steps: [
        'Keep the elbow bend fixed and sweep the arms out wide.',
        'Lift until the arms are level with the back.',
        'Squeeze between the shoulder blades for a moment.',
        'Lower slowly back to the start.',
      ],
      cues: ['Arms out wide', 'Soft, fixed elbows', 'Chest stays low'],
      mistakes: [
        'Using weights that are too heavy and swinging them up.',
        'Standing up as the arms lift.',
        'Bending the elbows more to turn it into a row.',
        'Shrugging the shoulders up to the ears.',
      ],
      breathing: 'Breathe out as the arms go out, breathe in as they lower.',
      tempo: 'About 1 second out, a short pause, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Arms hang', pelvis: { pos: [0, 0.85, -0.2], pitch: 62 }, neck: { flex: -14 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 62, plane: 8, twist: -90 }, elbow: 20 }, R: 'mirror' } },
      top: { label: 'Arms wide', pelvis: { pos: [0, 0.85, -0.2], pitch: 62 }, neck: { flex: -14 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 88, plane: 88, twist: -90 }, elbow: 20 }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.8], holds: { top: 0.4, hang: 0.3 },
  },
  renegadeRow: {
    camera: { yaw: 50, pitch: 14 },
    props: DB2,
    muscles: { primary: ['lats', 'core'], secondary: ['upperBack', 'shoulders', 'obliques', 'triceps'] },
    coaching: {
      setup: [
        'Set up in a high plank with hands on the dumbbell handles, directly under the shoulders.',
        'Feet wider than hip-width for balance.',
        'One straight line from head to heels, glutes and abs switched on.',
      ],
      steps: [
        'Press one dumbbell firmly into the floor.',
        'Row the other dumbbell up beside the ribs, elbow close to the body.',
        'Lower it back to the floor under control.',
        'Repeat on the other side, keeping the hips level the whole time.',
      ],
      cues: ['Hips square to the floor', 'Push the floor away', 'Elbow to the hip'],
      mistakes: [
        'Rotating the hips and chest up as you row.',
        'Hips sagging or piking up in the air.',
        'Feet too close together, which makes the body tip.',
        'Dropping the dumbbell back to the floor.',
      ],
      breathing: 'Breathe out as you row, breathe in as you lower.',
      tempo: 'About 1 second up, 1 second down, a short reset between sides.',
    },
    keys: {
      plank: { label: 'Plank', pelvis: { pos: [0, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.2, 0.13, -0.03], elbow: 'back' }, R: 'mirror' } },
      rowR: { label: 'Row right', pelvis: { pos: [0.02, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.2, 0.13, -0.03], elbow: 'back' }, R: { hand: [-0.2, 0.5, -0.3], elbow: [-0.2, 1, -0.6] } } },
      rowL: { label: 'Row left', pelvis: { pos: [-0.02, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { R: { hand: [-0.2, 0.13, -0.03], elbow: 'back' }, L: { hand: [0.2, 0.5, -0.3], elbow: [0.2, 1, -0.6] } } },
    },
    seq: ['plank', 'rowR', 'plank', 'rowL'], tempo: [1.0, 1.3, 1.0, 1.3], holds: { rowR: 0.3, rowL: 0.3, plank: 0.3 },
  },
  superman: {
    camera: { yaw: 60, pitch: 16 },
    muscles: { primary: ['lowerBack', 'upperBack'], secondary: ['glutes', 'hamstrings', 'lats', 'shoulders'] },
    coaching: {
      setup: [
        'Lie face down with legs straight and arms reaching overhead.',
        'Forehead just off the floor, eyes looking down.',
        'Squeeze the glutes lightly.',
      ],
      steps: [
        'Lift the chest, arms and thighs off the floor together.',
        'For the hold, keep them up and add small pulses.',
        'For pulls, keep everything lifted and sweep the elbows down and back to the sides, like a lat pulldown.',
        'Reach the arms back out overhead, then lower with control when the set is done.',
      ],
      cues: ['Chest and thighs up', 'Elbows to the back pockets', 'Long neck, eyes down'],
      mistakes: [
        'Cranking the head back to look forward, which strains the neck.',
        'Bending the knees instead of lifting from the hips.',
        'Jerking up too high and pinching the lower back.',
        'Letting the arms drop to the floor during the pull.',
      ],
      breathing: 'Breathe out as you lift or pull, keep breathing steadily in the hold.',
      tempo: 'Lift and hold 1 to 2 seconds at each position, or pulses of about 1 second.',
    },
    keys: {
      down: { label: 'Face down', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, neck: { flex: 10 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 170, plane: 12 }, elbow: 5 }, R: 'mirror' } },
      lift: { label: 'Lift', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -22 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 170, plane: 12 }, elbow: 5 }, R: 'mirror' } },
      pull: { label: 'Elbows back', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -23 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 55, plane: 115, twist: -38 }, elbow: 100 }, R: 'mirror' } },
      sweep: { label: 'Sweep', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -23 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 112, plane: 108, twist: -60 }, elbow: 30 }, R: 'mirror' } },
    },
    seq: ['down', 'lift', 'sweep', 'pull', 'sweep', 'lift'], tempo: [1.0, 0.7, 0.7, 0.7, 0.7, 1.0], holds: { lift: 0.4, sweep: 0, pull: 0.5, down: 0.4 },
  },
  supermanYtw: {
    camera: { yaw: 30, pitch: 30 },
    muscles: { primary: ['upperBack', 'shoulders'], secondary: ['traps', 'lowerBack'] },
    coaching: {
      setup: [
        'Lie face down with legs straight and toes pointed.',
        'Forehead just off the floor, eyes looking down.',
        'Arms reaching overhead in a Y, thumbs pointing up.',
      ],
      steps: [
        'Lift the chest slightly and raise the arms off the floor in a Y.',
        'Sweep the arms out to a T, level with the shoulders, still off the floor.',
        'Bend the elbows and pull them down beside the ribs to a W, squeezing the shoulder blades together.',
        'Reach back out to the Y and repeat.',
      ],
      cues: ['Thumbs up', 'Squeeze the shoulder blades', 'Long neck'],
      mistakes: [
        'Lifting the head and looking forward.',
        'Arching hard through the lower back to get the arms higher.',
        'Letting the arms touch the floor between positions.',
        'Shrugging the shoulders towards the ears.',
      ],
      breathing: 'Breathe out as you move into each letter, breathe in as you hold.',
      tempo: 'Hold each letter for 1 to 2 seconds.',
    },
    keys: {
      Y: { label: 'Y', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 145, plane: 102, twist: 90 }, elbow: 3 }, R: 'mirror' } },
      T: { label: 'T', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 90, plane: 108, twist: 90 }, elbow: 3 }, R: 'mirror' } },
      W: { label: 'W', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 55, plane: 118, twist: -38 }, elbow: 100 }, R: 'mirror' } },
    },
    seq: ['Y', 'T', 'W'], tempo: [1.2, 1.2, 1.4], holds: { Y: 0.6, T: 0.6, W: 0.6 },
  },
  kbFarmersWalk: {
    camera: { yaw: 30 },
    props: [{ type: 'kettlebell', hand: 'R', grip: 'hang' }],
    muscles: { primary: ['core', 'obliques', 'forearms'], secondary: ['traps', 'glutes', 'upperBack'] },
    coaching: {
      setup: [
        'Pick up the kettlebell in one hand with a flat back, then stand tall.',
        'Arm long by your side, shoulders level.',
        'Free arm relaxed.',
      ],
      steps: [
        'Walk with short, steady steps at a normal pace.',
        'Keep the trunk tall and do not lean towards or away from the bell.',
        'Grip the handle hard and keep the shoulder down.',
        'Walk down the driveway, put the bell down with a flat back, swap hands and walk back.',
      ],
      cues: ['Walk tall', 'Shoulders level', 'Grip hard'],
      mistakes: [
        'Leaning towards the bell with every step.',
        'Letting the bell swing and bang the leg.',
        'Rushing with long strides that make the trunk wobble.',
        'Picking the bell up with a rounded back.',
      ],
      breathing: 'Breathe steadily, keeping a light brace.',
      tempo: 'A controlled walking pace, around 20 to 30 metres per side.',
    },
    keys: walk((ph) => ({ L: swing('L', ph), R: { shoulder: { elev: 11, plane: 90 }, elbow: 2 } })),
    seq: WALK_SEQ, tempo: WALK_TEMPO, holds: WALK_HOLDS,
  },
  farmersWalk: {
    camera: { yaw: 30 },
    props: [{ type: 'dumbbell', hand: 'R' }],
    muscles: { primary: ['core', 'obliques', 'forearms'], secondary: ['traps', 'glutes', 'upperBack'] },
    coaching: {
      setup: [
        'Pick up one dumbbell with a flat back and stand tall.',
        'Arm long by your side, palm facing your leg, shoulders level.',
        'Free arm relaxed.',
      ],
      steps: [
        'Walk with short, steady steps at a normal pace.',
        'Stay tall and resist the pull of the dumbbell to the side.',
        'Keep the shoulder on the loaded side down and back.',
        'Walk down the driveway, swap hands and walk back.',
      ],
      cues: ['One dumbbell, stay level', 'Walk tall', 'Short, smooth steps'],
      mistakes: [
        'Leaning towards the dumbbell.',
        'Hiking the opposite hip or shoulder to balance.',
        'Letting the dumbbell swing into the leg.',
        'Holding the breath for the whole walk.',
      ],
      breathing: 'Breathe steadily, keeping a light brace.',
      tempo: 'A controlled walking pace, around 20 to 30 metres per side.',
    },
    keys: walk((ph) => ({ L: swing('L', ph), R: { shoulder: { elev: 8, plane: 90 }, elbow: 2, turn: 90 } })),
    seq: WALK_SEQ, tempo: WALK_TEMPO, holds: WALK_HOLDS,
  },
  dbFarmersWalk: {
    camera: { yaw: 30 },
    props: DB2,
    muscles: { primary: ['forearms', 'traps', 'core'], secondary: ['upperBack', 'glutes', 'quads'] },
    coaching: {
      setup: [
        'Pick up a dumbbell in each hand with a flat back and stand tall.',
        'Arms long by your sides, palms facing in.',
        'Shoulders down and back, chest proud.',
      ],
      steps: [
        'Walk with short, steady steps at a normal pace.',
        'Keep the dumbbells still at your sides.',
        'Stay tall with the ribs stacked over the hips.',
        'Walk for the set distance or time, then put the dumbbells down with a flat back.',
      ],
      cues: ['Tall and steady', 'Shoulders down and back', 'Squeeze the handles'],
      mistakes: [
        'Shrugging the shoulders up towards the ears.',
        'Leaning forward and looking at the feet.',
        'Letting the dumbbells swing.',
        'Rushing with long strides.',
      ],
      breathing: 'Breathe steadily, keeping a light brace.',
      tempo: 'A controlled walking pace, around 20 to 40 metres.',
    },
    keys: walk(() => ({ L: { shoulder: { elev: 8, plane: 90 }, elbow: 2, turn: 90 }, R: 'mirror' })),
    seq: WALK_SEQ, tempo: WALK_TEMPO, holds: WALK_HOLDS,
  },
  dbOverheadCarry: {
    camera: { yaw: 30 },
    props: DB2,
    muscles: { primary: ['shoulders', 'core'], secondary: ['triceps', 'traps', 'upperBack'] },
    coaching: {
      setup: [
        'Press both dumbbells overhead and lock the elbows out.',
        'Arms beside the ears, dumbbells over the middle of the feet.',
        'Ribs pulled down and glutes lightly squeezed.',
      ],
      steps: [
        'Walk with short, steady steps.',
        'Keep the arms locked and the dumbbells stacked over the shoulders.',
        'Stay tall without arching the lower back.',
        'Lower the dumbbells to the shoulders under control when you finish.',
      ],
      cues: ['Arms locked out', 'Ribs down', 'Walk tall'],
      mistakes: [
        'Arching the lower back and flaring the ribs.',
        'Letting the dumbbells drift forward of the head.',
        'Bent, soft elbows that tire the triceps.',
        'Going too heavy to keep the arms steady.',
      ],
      breathing: 'Breathe steadily behind a braced trunk.',
      tempo: 'A controlled walking pace, around 15 to 30 metres.',
    },
    keys: walk(() => ({ L: { hand: [0.23, 1.915, -0.02], elbow: 'out' }, R: 'mirror' })),
    seq: WALK_SEQ, tempo: WALK_TEMPO, holds: WALK_HOLDS,
  },
  kbHighPull: {
    camera: { yaw: 60 },
    props: [{ type: 'kettlebell', hand: 'both' }],
    muscles: { primary: ['traps', 'upperBack', 'glutes'], secondary: ['shoulders', 'hamstrings', 'biceps', 'core'] },
    coaching: {
      setup: [
        'Feet a little wider than hip-width, kettlebell on the floor between the feet.',
        'Hinge at the hips with a flat back and grip the handle with both hands.',
        'Shoulders slightly in front of the bell, arms long.',
      ],
      steps: [
        'Hike the bell back between the legs, keeping the back flat.',
        'Drive the hips forward hard and stand tall.',
        'As the bell floats up, pull the elbows high and wide.',
        'Bring the bell to chest height with the elbows above the hands, then let it drop back into the hinge.',
      ],
      cues: ['Hips first, then pull', 'Elbows high', 'Bell to the chest'],
      mistakes: [
        'Lifting with the arms before the hips have finished.',
        'Squatting the bell up instead of hinging.',
        'Rounding the back at the bottom.',
        'Pulling the bell higher than the chest and shrugging the shoulders up.',
      ],
      breathing: 'Breathe out sharply as the hips drive, breathe in as the bell drops.',
      tempo: 'Quick and snappy up, controlled on the way back into the hinge.',
    },
    keys: {
      hinge: { label: 'Hinge', pelvis: { pos: [0, 0.8, -0.2], pitch: 50 }, neck: { flex: -14 },
        legs: { L: { foot: [0.17, 0.07, 0.02], toeOut: 12, knee: [0.3, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.045, 0.575, 0.11], elbow: 'out' }, R: 'mirror' } },
      drive: { label: 'Hips through', pelvis: { pos: [0, 0.925, 0] }, neck: { flex: 0 },
        legs: { L: { foot: [0.17, 0.07, 0.02], toeOut: 12, knee: [0.3, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.065, 0.88, 0.15], elbow: 'out' }, R: 'mirror' } },
      pull: { label: 'Elbows high', pelvis: { pos: [0, 0.93, 0] }, spine: { flex: -2 },
        legs: { L: { foot: [0.17, 0.07, 0.02], toeOut: 12, knee: [0.3, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.09, 1.2, 0.2], elbow: [1, 0.8, -0.3] }, R: 'mirror' } },
    },
    seq: ['hinge', 'drive', 'pull', 'drive'], tempo: [0.5, 0.35, 0.55, 0.6], holds: { hinge: 0.25, drive: 0, pull: 0.2 },
  },
  ringHang: {
    camera: { yaw: 40, pitch: 4 },
    props: [{ type: 'rings', top: 2.9 }],
    muscles: { primary: ['forearms', 'lats'], secondary: ['shoulders', 'core'] },
    coaching: {
      setup: [
        'Set the rings high enough that your feet clear the floor with the arms straight.',
        'Grip the rings firmly with the palms facing each other or facing forward.',
        'Step or jump up to hang with the arms long.',
      ],
      steps: [
        'Pull the shoulders gently down away from the ears.',
        'Keep the legs together with a light hollow in the trunk.',
        'Stay still: no swinging.',
        'Hold for the set time, then step down with control.',
      ],
      cues: ['Long arms', 'Shoulders packed', 'Legs quiet'],
      mistakes: [
        'Letting the shoulders shrug up to the ears and sit on the joint.',
        'Swinging or kicking the legs.',
        'Bending the elbows to make it easier.',
        'Dropping off suddenly at the end.',
      ],
      breathing: 'Slow, steady breaths through the hold.',
      tempo: 'Hold for the set time, around 20 to 40 seconds.',
    },
    keys: {
      a: { label: 'Hang', pelvis: { pos: [0, 1.35, 0.035], pitch: -2 },
        legs: { L: { hip: { flex: 6 }, knee: 8, ankle: -20 }, R: 'mirror' },
        arms: { L: { hand: [0.24, 2.35, 0], elbow: 'out' }, R: 'mirror' } },
      b: { label: 'Breathe', pelvis: { pos: [0, 1.355, 0.035], pitch: -2 }, spine: { flex: -1.5 },
        legs: { L: { hip: { flex: 7 }, knee: 9, ankle: -20 }, R: 'mirror' },
        arms: { L: { hand: [0.24, 2.35, 0], elbow: 'out' }, R: 'mirror' } },
    },
    seq: ['a', 'b'], tempo: [1.8, 2.2], holds: { a: 0.3, b: 0.4 },
  },
  ringChinup: {
    camera: { yaw: 50, pitch: 4 },
    props: [{ type: 'rings', top: 2.9 }],
    muscles: { primary: ['lats', 'biceps'], secondary: ['upperBack', 'forearms', 'core'] },
    coaching: {
      setup: [
        'Set the rings high enough that your feet clear the floor.',
        'Grip with the palms facing you; the rings can turn as you pull.',
        'Hang with long arms, shoulders pulled down, legs together.',
      ],
      steps: [
        'Pull the shoulder blades down to start the pull.',
        'Drive the elbows down towards the ribs and pull the chest up to the rings.',
        'Finish with the chest near the rings and the chin above them.',
        'Lower slowly all the way back to long arms.',
      ],
      cues: ['Chest to the rings', 'Elbows down to the ribs', 'Control down'],
      mistakes: [
        'Kicking or swinging the legs to get up.',
        'Half reps that stop short of long arms at the bottom.',
        'Reaching the chin forward instead of lifting the chest.',
        'Dropping fast on the way down.',
      ],
      breathing: 'Breathe out as you pull up, breathe in as you lower.',
      tempo: 'About 1 to 2 seconds up, a short pause, 2 to 3 seconds down.',
    },
    keys: {
      hang: { label: 'Long arms', pelvis: { pos: [0, 1.35, 0.035], pitch: -2 },
        legs: { L: { hip: { flex: 8 }, knee: 25, ankle: -20 }, R: 'mirror' },
        arms: { L: { hand: [0.24, 2.35, 0], elbow: [0.3, -0.3, 1] }, R: 'mirror' } },
      half: { label: 'Halfway', pelvis: { pos: [0, 1.6, 0.03], pitch: -6 },
        legs: { L: { hip: { flex: 10 }, knee: 28, ankle: -20 }, R: 'mirror' },
        arms: { L: { hand: [0.24, 2.35, 0], elbow: [0.15, -1, 0.8] }, R: 'mirror' } },
      top: { label: 'Chest to rings', pelvis: { pos: [0, 1.86, 0.03], pitch: -12 },
        legs: { L: { hip: { flex: 12 }, knee: 30, ankle: -20 }, R: 'mirror' },
        arms: { L: { hand: [0.24, 2.35, 0], elbow: [0.15, -1, 0.7] }, R: 'mirror' } },
    },
    seq: ['hang', 'half', 'top', 'half'], tempo: [0.6, 0.6, 1.0, 1.0], holds: { hang: 0.4, half: 0, top: 0.35 },
  },
  ringRow: {
    camera: { yaw: 70, pitch: 6 },
    props: [{ type: 'rings', top: 2.4 }],
    muscles: { primary: ['lats', 'upperBack'], secondary: ['biceps', 'core', 'glutes'] },
    coaching: {
      setup: [
        'Set the rings around waist height and hold one in each hand.',
        'Walk the feet forward and lean back until the arms are straight, heels on the floor.',
        'Body in one straight line from heels to head, glutes switched on.',
      ],
      steps: [
        'Pull the chest up to the rings, driving the elbows back beside the ribs.',
        'Keep the body straight like a plank the whole way.',
        'Squeeze the shoulder blades together at the top.',
        'Lower slowly back to straight arms.',
      ],
      cues: ['Body like a plank', 'Chest to the rings', 'Walk the feet in to make it harder'],
      mistakes: [
        'Hips sagging towards the floor.',
        'Leading with the chin instead of the chest.',
        'Shrugging the shoulders up towards the ears.',
        'Dropping back down instead of lowering.',
      ],
      breathing: 'Breathe out as you pull, breathe in as you lower.',
      tempo: 'About 1 second up, a short squeeze, 2 seconds down.',
    },
    keys: {
      hang: { label: 'Arms long', pelvis: { pos: [0, 0.636, -0.051], pitch: -50 },
        legs: { L: { foot: [0.1, 0.09, 0.6], knee: [0, 1, 0.6], ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.22, 1.16, 0.06], elbow: 'down' }, R: 'mirror' } },
      top: { label: 'Chest to rings', pelvis: { pos: [0, 0.803, 0.137], pitch: -33 },
        legs: { L: { foot: [0.1, 0.09, 0.6], knee: [0, 1, 0.8], ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.22, 1.16, 0.06], elbow: [0.4, -0.6, -0.8] }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
};