/*
  © 2026 Wayne Cavanagh / Flaux. All rights reserved.
  3D movement data, pulling, arms and carries: see js/moves/README.md.
*/
const FEET = { L: { foot: [0.12, 0.07, 0], toeOut: 8 }, R: 'mirror' };
const NOTES = { setup: [], steps: [], cues: [], mistakes: [], breathing: '', tempo: '' };
const DB2 = [{ type: 'dumbbell', hand: 'L' }, { type: 'dumbbell', hand: 'R' }];

export default {
  dbCurl: {
    camera: { yaw: 40 },
    props: DB2,
    muscles: { primary: ['biceps'], secondary: ['forearms'] },
    coaching: NOTES,
    keys: {
      down: { label: 'Arms long', legs: FEET,
        arms: { L: { shoulder: { elev: 4, plane: 0 }, elbow: 8 }, R: 'mirror' } },
      up: { label: 'Squeeze', legs: FEET,
        arms: { L: { shoulder: { elev: 10, plane: 0 }, elbow: 138 }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [1.0, 2.0], holds: { up: 0.35, down: 0.3 },
  },
  barbellCurl: {
    camera: { yaw: 40 },
    props: [{ type: 'barbell', length: 1.5, plate: 0.13 }],
    muscles: { primary: ['biceps'], secondary: ['forearms'] },
    coaching: NOTES,
    keys: {
      down: { label: 'Arms long', legs: FEET,
        arms: { L: { shoulder: { elev: 12, plane: 20 }, elbow: 8 }, R: 'mirror' } },
      up: { label: 'Squeeze', legs: FEET,
        arms: { L: { shoulder: { elev: 12, plane: 12 }, elbow: 138 }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [1.0, 2.0], holds: { up: 0.35, down: 0.3 },
  },
  dbShrug: {
    camera: { yaw: 20 },
    props: DB2,
    coaching: NOTES,
    keys: {
      down: { label: 'Arms long', legs: FEET,
        arms: { L: { shoulder: { elev: 7, plane: 90 }, elbow: 4 }, R: 'mirror' } },
      up: { label: 'Shoulders up', legs: FEET, neck: { flex: 8 },
        arms: { L: { shoulder: { elev: 7, plane: 90 }, elbow: 2 }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [0.8, 1.4], holds: { up: 0.8, down: 0.3 },
  },
  dbUprightRow: {
    camera: { yaw: 30 },
    props: DB2,
    coaching: NOTES,
    keys: {
      down: { label: 'Arms long', legs: FEET, arms: { L: { hand: [0.12, 0.84, 0.09], elbow: [1, 0, 0] }, R: 'mirror' } },
      up: { label: 'Elbows high', legs: FEET, arms: { L: { hand: [0.12, 1.22, 0.1], elbow: [1, 0.5, 0] }, R: 'mirror' } },
    },
    seq: ['down', 'up'], tempo: [1.0, 1.8], holds: { up: 0.3, down: 0.3 },
  },
  kbRackHold: {
    camera: { yaw: 30 },
    props: [{ type: 'kettlebell', hand: 'R' }],
    coaching: NOTES,
    keys: {
      a: { label: 'Breathe in', legs: FEET, spine: { flex: -1.5 },
        arms: { L: { shoulder: { elev: 6, plane: 90 }, elbow: 10 }, R: { hand: [-0.1, 1.18, 0.15], elbow: [-0.05, -1, 0.35], wrist: 65 } } },
      b: { label: 'Breathe out', legs: FEET, spine: { flex: 0.5 },
        arms: { L: { shoulder: { elev: 5, plane: 90 }, elbow: 10 }, R: { hand: [-0.1, 1.175, 0.15], elbow: [-0.05, -1, 0.35], wrist: 65 } } },
    },
    seq: ['a', 'b'], tempo: [1.8, 2.2], holds: { a: 0.3, b: 0.4 },
  },
  kbSuitcaseHold: {
    camera: { yaw: 20 },
    props: [{ type: 'kettlebell', hand: 'R' }],
    coaching: NOTES,
    keys: {
      a: { label: 'Breathe in', legs: FEET, spine: { flex: -1.5 },
        arms: { L: { shoulder: { elev: 6, plane: 90 }, elbow: 10 }, R: { shoulder: { elev: 11, plane: 90 }, elbow: 2 } } },
      b: { label: 'Breathe out', legs: FEET, spine: { flex: 0.5 },
        arms: { L: { shoulder: { elev: 5, plane: 90 }, elbow: 10 }, R: { shoulder: { elev: 11, plane: 90 }, elbow: 2 } } },
    },
    seq: ['a', 'b'], tempo: [1.8, 2.2], holds: { a: 0.3, b: 0.4 },
  },
  barbellRow: {
    camera: { yaw: 60 },
    props: [{ type: 'barbell', length: 1.5, plate: 0.13 }],
    coaching: NOTES,
    keys: {
      hang: { label: 'Arms long', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.23, 0.63, 0.12], elbow: 'back' }, R: 'mirror' } },
      top: { label: 'Bar to belly', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.23, 0.95, 0.06], elbow: [0.25, 0.6, -1] }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  dbRow: {
    camera: { yaw: 60 },
    props: DB2,
    coaching: NOTES,
    keys: {
      hang: { label: 'Arms long', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.2, 0.63, 0.12], elbow: 'back' }, R: 'mirror' } },
      top: { label: 'Squeeze', pelvis: { pos: [0, 0.86, -0.2], pitch: 52 }, neck: { flex: -16 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { hand: [0.21, 0.96, 0.0], elbow: [0.15, 0.6, -1] }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  kbRow: {
    camera: { yaw: 60 },
    props: [{ type: 'kettlebell', hand: 'R' }],
    coaching: NOTES,
    keys: {
      hang: { label: 'Arm long', pelvis: { pos: [0, 0.84, -0.2], pitch: 55 }, neck: { flex: -16 },
        legs: { L: { foot: [0.14, 0.07, 0.14], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.14, 0.07, -0.34], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.14, 0.62, 0.12], elbow: [1, 0, -0.3] }, R: { hand: [-0.2, 0.62, 0.14], elbow: 'back' } } },
      top: { label: 'Elbow to hip', pelvis: { pos: [0, 0.84, -0.2], pitch: 55 }, neck: { flex: -16 },
        legs: { L: { foot: [0.14, 0.07, 0.14], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.14, 0.07, -0.34], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.14, 0.62, 0.12], elbow: [1, 0, -0.3] }, R: { hand: [-0.21, 0.9, -0.04], elbow: [-0.1, 0.5, -1] } } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.6], holds: { top: 0.4, hang: 0.3 },
  },
  dbRowSingle: {
    camera: { yaw: 60 },
    props: [{ type: 'dumbbell', hand: 'R' }, { type: 'bench', pos: [0.28, 0, 0.8], size: [0.35, 0.45, 1.2] }],
    coaching: NOTES,
    keys: {
      hang: { label: 'Long arm', pelvis: { pos: [0, 0.82, -0.2], pitch: 72 }, neck: { flex: -10 },
        legs: { L: { foot: [0.15, 0.07, 0.05], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.15, 0.07, -0.4], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.24, 0.48, 0.3], elbow: 'back', palm: 'floor' }, R: { hand: [-0.2, 0.46, 0.25], elbow: 'back' } } },
      top: { label: 'Elbow to hip', pelvis: { pos: [0, 0.82, -0.2], pitch: 72 }, neck: { flex: -10 },
        legs: { L: { foot: [0.15, 0.07, 0.05], toeOut: 6, knee: [0.1, 0, 1] }, R: { foot: [-0.15, 0.07, -0.4], toeOut: 12, knee: [-0.1, 0, 1] } },
        arms: { L: { hand: [0.24, 0.48, 0.3], elbow: 'back', palm: 'floor' }, R: { hand: [-0.21, 0.8, -0.05], elbow: [-0.1, 0.6, -1] } } },
    },
    seq: ['hang', 'top'], tempo: [1.1, 1.8], holds: { top: 0.4, hang: 0.3 },
  },
  dbRearDeltFly: {
    camera: { yaw: 30, pitch: 14 },
    props: DB2,
    coaching: NOTES,
    keys: {
      hang: { label: 'Arms hang', pelvis: { pos: [0, 0.85, -0.2], pitch: 62 }, neck: { flex: -14 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 62, plane: 8, twist: -90 }, elbow: 20 }, R: 'mirror' } },
      top: { label: 'Arms wide', pelvis: { pos: [0, 0.85, -0.2], pitch: 62 }, neck: { flex: -14 },
        legs: { L: { foot: [0.13, 0.07, 0.02], toeOut: 8, knee: [0.15, 0, 1] }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 88, plane: 88, twist: -90 }, elbow: 20 }, R: 'mirror' } },
    },
    seq: ['hang', 'top'], tempo: [1.0, 1.8], holds: { top: 0.4, hang: 0.3 },
  },
  renegadeRow: {
    camera: { yaw: 50, pitch: 14 },
    props: DB2,
    coaching: NOTES,
    keys: {
      plank: { label: 'Plank', pelvis: { pos: [0, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.2, 0.13, -0.03], elbow: 'back' }, R: 'mirror' } },
      rowR: { label: 'Row right', pelvis: { pos: [0.02, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { L: { hand: [0.2, 0.13, -0.03], elbow: 'back' }, R: { hand: [-0.2, 0.5, -0.3], elbow: [-0.2, 1, -0.6] } } },
      rowL: { label: 'Row left', pelvis: { pos: [-0.02, 0.47, -0.45], pitch: 67 }, neck: { flex: 8 },
        legs: { L: { foot: [0.2, 0.122, -1.22], knee: 'down', ankle: 0 }, R: 'mirror' },
        arms: { R: { hand: [-0.2, 0.13, -0.03], elbow: 'back' }, L: { hand: [0.2, 0.5, -0.3], elbow: [0.2, 1, -0.6] } } },
    },
    seq: ['plank', 'rowR', 'plank', 'rowL'], tempo: [1.0, 1.3, 1.0, 1.3], holds: { rowR: 0.3, rowL: 0.3, plank: 0.3 },
  },
  superman: {
    camera: { yaw: 60, pitch: 16 },
    coaching: NOTES,
    keys: {
      down: { label: 'Face down', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, neck: { flex: 10 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 170, plane: 12 }, elbow: 5 }, R: 'mirror' } },
      lift: { label: 'Lift', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -18 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 170, plane: 12 }, elbow: 5 }, R: 'mirror' } },
      pull: { label: 'Elbows back', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -20 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 55, plane: 115, twist: -60 }, elbow: 100 }, R: 'mirror' } },
      sweep: { label: 'Sweep', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -19 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: -14, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 112, plane: 108, twist: -60 }, elbow: 30 }, R: 'mirror' } },
    },
    seq: ['down', 'lift', 'sweep', 'pull', 'sweep', 'lift'], tempo: [1.0, 0.7, 0.7, 0.7, 0.7, 1.0], holds: { lift: 0.4, sweep: 0, pull: 0.5, down: 0.4 },
  },
  supermanYtw: {
    camera: { yaw: 30, pitch: 30 },
    coaching: NOTES,
    keys: {
      Y: { label: 'Y', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 150, plane: 45, twist: 90 }, elbow: 3 }, R: 'mirror' } },
      T: { label: 'T', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 90, plane: 118, twist: 90 }, elbow: 3 }, R: 'mirror' } },
      W: { label: 'W', pelvis: { pos: [0, 'auto', 0], pitch: 90 }, spine: { flex: -10 }, neck: { flex: 8 },
        legs: { L: { hip: { flex: 0, abd: 4 }, knee: 0, ankle: -45 }, R: 'mirror' },
        arms: { L: { shoulder: { elev: 55, plane: 118, twist: -60 }, elbow: 100 }, R: 'mirror' } },
    },
    seq: ['Y', 'T', 'W'], tempo: [1.2, 1.2, 1.4], holds: { Y: 0.6, T: 0.6, W: 0.6 },
  },
};